# Generated by Django 4.0.3 on 2022-03-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('parameters', models.CharField(blank=True, max_length=255)),
                ('headers', models.CharField(blank=True, max_length=255)),
                ('result', models.TextField(blank=True)),
                ('revive_moment', models.DateTimeField()),
                ('expiry_moment', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DownloadedInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('exporter_type', models.TextField(max_length=2048)),
                ('download_info_parameters', models.TextField(max_length=2048)),
                ('download_history_parameters', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='SourceApiActuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter_type', models.CharField(max_length=255, unique=True)),
                ('check_error_message', models.TextField(blank=True, null=True)),
                ('last_check_moment', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=50)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_data', to='fin_storage.exporter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exporter',
            constraint=models.UniqueConstraint(fields=('unique_code',), name='unique_code'),
        ),
        migrations.AddField(
            model_name='downloadedinterval',
            name='exporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_intervals', to='fin_storage.exporter'),
        ),
        migrations.AddConstraint(
            model_name='cacheditem',
            constraint=models.UniqueConstraint(fields=('url', 'parameters', 'headers'), name='UQ_url_param_headers'),
        ),
        migrations.AddConstraint(
            model_name='instrumentvalue',
            constraint=models.UniqueConstraint(fields=('exporter', 'moment'), name='unique_exporter_moment'),
        ),
        migrations.AddConstraint(
            model_name='downloadedinterval',
            constraint=models.UniqueConstraint(fields=('exporter', 'date_from'), name='unique_exporter_date_from'),
        ),
    ]
